export type TagCategory = 'personality' | 'temperament' | 'identity' | 'interest';

export const CATEGORY_LABELS: Record<TagCategory, string> = {
  personality: '性格',
  temperament: '气质',
  identity: '身份',
  interest: '兴趣',
};

export const CATEGORY_ORDER: TagCategory[] = ['personality', 'temperament', 'identity', 'interest'];

const TAG_CATEGORY_MAP: Record<string, TagCategory> = {
  // 性格
  '理性': 'personality',
  '毒舌': 'personality',
  '开朗': 'personality',
  '好奇': 'personality',
  '幽默': 'personality',
  '温柔': 'personality',
  '热血': 'personality',
  '活泼': 'personality',
  '沙雕': 'personality',
  '病娇': 'personality',
  '偏执': 'personality',
  '占有欲': 'personality',
  '浪漫': 'personality',
  '健谈': 'personality',
  '内向': 'personality',
  '外向': 'personality',
  '傲娇': 'personality',
  '主动': 'personality',
  '乐观': 'personality',
  '暖心': 'personality',
  '倾听': 'personality',
  '热情': 'personality',
  '元气': 'personality',
  '阳光': 'personality',
  '温暖': 'personality',
  '自来熟': 'personality',
  '话痨': 'personality',
  '黏人': 'personality',
  '粘人': 'personality',
  // 气质
  '高冷': 'temperament',
  '疏离': 'temperament',
  '慵懒': 'temperament',
  '神秘': 'temperament',
  '忧郁': 'temperament',
  '文雅': 'temperament',
  '洒脱': 'temperament',
  '清冷': 'temperament',
  '治愈': 'temperament',
  '冷静': 'temperament',
  '孤傲': 'temperament',
  '内敛': 'temperament',
  '冰冷': 'temperament',
  '冷淡': 'temperament',
  '冷漠': 'temperament',
  '外冷': 'temperament',
  '安静': 'temperament',
  '沉默': 'temperament',
  '醉意': 'temperament',
  '惜字如金': 'temperament',
  // 身份
  '极客': 'identity',
  '剑客': 'identity',
  '文艺': 'identity',
  '书卷气': 'identity',
  '游戏宅': 'identity',
  '军师': 'identity',
  '博学': 'identity',
  '学者': 'identity',
  '医生': 'identity',
  '教师': 'identity',
  '律师': 'identity',
  '黑客': 'identity',
  '侦探': 'identity',
  '神明': 'identity',
  '精灵': 'identity',
  '机器人': 'identity',
  // 兴趣
  '哲思': 'interest',
  '运动': 'interest',
  '音乐': 'interest',
  '阅读': 'interest',
  '旅行': 'interest',
  '美食': 'interest',
  '摄影': 'interest',
  '动漫': 'interest',
  '游戏': 'interest',
  '追星': 'interest',
  '天文': 'interest',
  '编程': 'interest',
  '绘画': 'interest',
};

export function categorizeTag(tag: string): TagCategory {
  return TAG_CATEGORY_MAP[tag] ?? 'personality';
}
